# Generated by Django 2.0.7 on 2018-07-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('is_done', models.BooleanField(default=False)),
                ('sdt', models.TimeField()),
                ('edt', models.TimeField()),
                ('headsign', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastus_id', models.IntegerField()),
                ('short_name', models.CharField(max_length=5)),
                ('long_name', models.CharField(max_length=100)),
                ('route_abbreviation', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastus_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('is_time_point', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='departure',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvta_data.Route'),
        ),
        migrations.AddField(
            model_name='departure',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pvta_data.Stop'),
        ),
    ]
