# Generated by Django 2.0.7 on 2018-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvta_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='hastus_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='hastus_id',
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
